deployment:
  tasks:
    - export DEPLOYPATH=/home1/uptbahasaummetro/public_html
    - /bin/cp -Rf * $DEPLOYPATH/
    - /bin/cp -Rf .htaccess .env.example .user.ini $DEPLOYPATH/
    - cd $DEPLOYPATH && php artisan optimize:clear || true
    - cd $DEPLOYPATH && php artisan migrate --force || true
